### ISSUE TITLE
Create roadmap

### ISSUE THREAD

**Issue by StarpTech** [apparatus/mu#68]
Hi @davidmarkclements @mcollina I think we should create a roadmap to work on the right things.
At the moment there are lots of ideas. We should focus on the minimum to make it operational.

I suggest

- [ ] Writing down the api interface

- [ ] Implement a logging interface

- [ ] Clear concept of error handling + implementation

- [ ] Implement an interface for payload validation 

- [ ] Make HTTP/TCP Transports stable.

**Comment by davidmarkclements** [comment]
hey @StarpTech 

> Writing down the api interface
yep

>  Implement a logging interface
this is done - mu.log is a [pino](http://npm.im/pino) instance

> Clear concept of error handling + implementation
yeah we're getting there

> Implement an interface for payload validation
not sure this should be part of core, I'll answer this on the issue you answered

> Make HTTP/TCP Transports stable.
tcp is approaching stability - although it'll need battletesting for sure, http still to do

**Comment by davidmarkclements** [comment]
let's use this issue as a bare bones roadmap for the moment

**Comment by tomdavidson** [comment]
What about a mesh transport similar to seneca mesh?

**Comment by davidmarkclements** [comment]
yah distributed transport is on the menu, potentially using https://www.npmjs.com/package/swim-hashring

**Comment by davidmarkclements** [comment]
it doesn't necessarily come under "minimum to make operational" though

**Comment by mcollina** [comment]
@davidmarkclements probably you'll just need https://github.com/mcollina/baseswim.

**Comment by davidmarkclements** [comment]
@mcollina yah thanks I realised that shortly after

**Comment by pelger** [comment]
@StarpTech PR in for HTTP transport - https://github.com/apparatus/mu/pull/74. Would welcome a review if you have bandwidth!

**Comment by pelger** [comment]
On SWIM, looking to implement discovery adapters most likely consul / etcd first, followed by a gossip based adapter. Agreed that we should pull together a more formal road map, will aim to pull one together for review soon!
